context('plushtoy', () => {
    beforeEach(() => {
        cy.loginAdmin();
        cy.goToAdminOverview();
    });

    it("should create a new plush toy", () => {
        cy.intercept('POST', '/api/v1/admin/product').as('createPlushToy');

        cy.getBySel('createButton').click()
        cy.get('input[name="name"]').type("New Test Tiger");
        cy.get('input[name="price"]').type("10");
        cy.get('textarea[name="description"]').type("This is a new Test Tiger generated by e2e");
        cy.get('input[name="taxClass"]').type("1");
        cy.get('input[name="weight"]').type("10");
        cy.get('select[name="color"]').select("RED");
        cy.get('select[name="size"]').select("SMALL");
        cy.get('input[name="hp"]').type("100");
        cy.get('input[name="strength"]').type("10");
        cy.getBySel('submitButton').click();

        cy.wait('@createPlushToy').its('response.statusCode').should('eq', 201);
        cy.getBySel('plushToyInfo').last().should('be.visible');
        cy.getBySel('plushToyInfo').last().should('contain', 'New Test Tiger', 'This is a new Test Tiger generated be e2e', 10);

        cy.get('.ng-trigger').should("contain", "PlushToy created successfully");
    });

    it("should edit an existing plush toy", () => {
        cy.intercept('PUT', '/api/v1/admin/product/*').as('editPlushToy');

        cy.getBySel('editButton').last().click();

        cy.get('input[name="name"]').clear().type("Updated Test Tiger");
        cy.get('textarea[name="description"]').clear().type("This is an updated Test Tiger generated by e2e");
        cy.get('input[name="price"]').clear().type("20");
        cy.get('input[name="taxClass"]').clear().type("2");
        cy.get('input[name="weight"]').clear().type("15");
        cy.get('select[name="color"]').select("BLUE");
        cy.get('select[name="size"]').select("MEDIUM");
        cy.get('input[name="hp"]').clear().type("150");
        cy.get('input[name="strength"]').clear().type("15");
        cy.getBySel('submitButton').click();

        cy.wait('@editPlushToy').its('response.statusCode').should('eq', 200);
        cy.getBySel("plushToyInfo").last().should('contain', 'Updated Test Tiger', 'This is a updated Test Tiger generated be e2e', 20);

        cy.get('.ng-trigger').should("contain", "PlushToy edited successfully");
    });

    it('should get delete on button press', () => {
        cy.getBySel("deleteButton").its('length').then((num) => {
            cy.getBySel("deleteButton").last().click();
            cy.getBySel("confirmModal").first().click()
            cy.getBySel("deleteButton").should("have.length", num - 1);
        });
    });
});
